---
title: "09_prescribed_burns_aqd"
author: "Puvvula"
date: "11/12/2021"
output: pdf_document
---

```{r}
library(tidyverse)
library(lubridate)
library(zoo)
library(splines)
library(tsModel)
library(dlnm)
library(mgcv)
library(ggstatsplot)
df<- read_csv("/work/jessebell/puvvula/aqd_final_data/pAsthma_imputed.csv")
#Formatting and creating new TS variables
df$date<- as.Date(df$date, format = "%m/%d/%Y")
df <- df %>% mutate(year = year(date),
                          month = month(date, label=TRUE),
                          day = day(date))
df$dow <- wday(as.Date(df$date, format = "%m/%d/%Y"))
weekdays1 <- c('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')
df$wDay <- factor((weekdays(df$date) %in% weekdays1), 
                       levels=c(FALSE, TRUE), labels=c('weekend', 'weekday'))
df$week_num<- week(ymd(df$date))
#year to quarter conversion use zoo library for as.nearmon function
yq <- as.yearqtr(as.yearmon(df$date, "%Y %m/%d/") + 1/12)
df$season <- factor(format(yq, "%q"), levels = 1:4,
                     labels = c("winter", "spring", "summer", "fall"))
#Save data with ts variables
write_csv(df,"/work/jessebell/puvvula/aqd_final_data/p_burn_asth.csv")
```

Start here

```{r}
library(tidyverse)
library(lubridate)
library(zoo)
library(splines)
library(tsModel)
library(dlnm)
library(mgcv)
library(ggpubr)
dat<- read_csv("/work/jessebell/puvvula/aqd_final_data/p_burn_asth.csv")
dat$month<-as.factor(dat$month)
dat$wDay<-as.factor(dat$wDay)
dat$dow<-as.factor(dat$dow)
dat$pres_burn<- as.factor(dat$pres_burn)
dat$year<- as.factor(dat$year)
#Excluding pollen dominant months
filter_month<- c("Jan","Feb","Mar","Apr","May")
df<- subset(dat, month %in% filter_month)
```

```{r}
#Pedatric asthma ED visits - differences
df %>% group_by(year,pres_burn) %>%
  summarise(days=n(),
            total=sum(p_ast),
            avg=mean(p_ast),
            sd=sd(p_ast),
            median = median(p_ast, na.rm = TRUE),
            IQR = IQR(p_ast, na.rm = TRUE))
ggboxplot(df,x="pres_burn", y="p_ast",
          color = "pres_burn",
          ylab = "Number of asthma ED visits", xlab = "Prescribed burn")
#Mean differences 
df1<-df %>% filter(year=="2019")
#t.test(p_ast~pres_burn, data=df1) #not using
wilcox.test(p_ast~pres_burn, alternative = "two.sided", data=df1)
##########################################
##########################################
#PM differences - differences
df %>% group_by(year,pres_burn) %>%
  summarise(days=n(),
            med=median(cp_07),
            avg=mean(cp_07),
            sd=sd(cp_07))
ggboxplot(df,x="pres_burn", y="p_ast",
          color = "pres_burn",
          ylab = "Number of asthma ED visits", xlab = "Prescribed burn")
#two sided t-test
df1<-df %>% filter(year=="2019")
#t.test(cp_07~pres_burn, data=df1) #switch to two sided wilcoxon test
wilcox.test(cp_07~pres_burn, alternative = "two.sided", data=df1)
```

```{r}
#Spearman-Rho correlations Ped-asthma and criteria pollutants col3-16
library(corrplot)
df_cor<- df[c(3:16)]
M<-cor(df_cor, method = "spearman", use = "complete.obs")
cor.mtest <- function(mat, ...) {
  mat <- as.matrix(mat)
  n <- ncol(mat)
  p.mat<- matrix(NA, n, n)
  diag(p.mat) <- 0
  for (i in 1:(n - 1)) {
    for (j in (i + 1):n) {
      tmp <- cor.test(mat[, i], mat[, j], ...)
      p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
    }
  }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
p.mat <- cor.mtest(df_cor)
col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))
cor_plt<-corrplot(M, method="color", col=col(200),  
         type="upper", order="original",
         tl.col="black", tl.srt=90, cl.cex = 1, tl.cex = 0.7, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.01, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE)
```


```{r}
#Start modeling with PM10 and pediatric asthma
#GLM
library(stats)
library(splines)
library(tsModel)
library(mda)
library(lattice)
library(MASS)
dat<- read_csv("/work/jessebell/puvvula/aqd_final_data/p_burn_asth.csv")
dat$month<-as.factor(dat$month)
dat$wDay<-as.factor(dat$wDay)
dat$dow<-as.factor(dat$dow)
dat$pres_burn<- as.factor(dat$pres_burn)
dat$year<- as.factor(dat$year)
dat$popln<- as.numeric(160554)
#Excluding pollen dominant months
filter_month<- c("Jan","Feb","Mar","Apr","May")
df<- subset(dat, month %in% filter_month)
#subset by year |||| PRESCRIBED BURNS AS BINARY VARIABLE
dat.m1<- df%>% filter(year=="2019")
#presribed burn yes or no and pediatric asthma
m1<-glm.nb(p_ast~as.factor(pres_burn)+offset(log(popln)),data = dat.m1)
(est <- cbind(Estimate = coef(m1), confint(m1)))
exp(est)
#interaction between pm10 and prescribed burns
m1<-glm.nb(p_ast~as.factor(pres_burn):cp_07+offset(log(popln)),data = dat.m1)
(est <- cbind(Estimate = coef(m1), confint(m1)))
exp(est)
# moving to GAM
library(mgcv)
mod.gam<- gam(p_ast ~ as.factor(pres_burn):cp_07,
         family=nb(link = log),
         method = "GCV.Cp",
         data=dat.m1) 
summary(mod.gam)
#deviance explained is 3.5%
##########################################################################
##########################################################################
#dlnm
```
